### ISSUE TITLE
Support explain options

### ISSUE THREAD

**Issue by abraham** [trilogy-libraries/activerecord-trilogy-adapter#31]
```ruby
$ scope.explain(:analyze)
=> DEPRECATION WARNING: The current database adapter, Trilogy, does not support explain options. To remove this warning, the adapter must implement `build_explain_clause(options = [])`.
```

Ref https://github.com/rails/rails/pull/47043

**Comment by jhawthorn** [comment]
This might actually be better solved in Rails. `build_explain_clause` should have been implemented on abstract_mysql_adapter, not mysql_adapter

**Comment by composerinteralia** [comment]
This adapter was merged into Rails, so that's now certainly the correctly place to address this.

**Comment by reid-rigo** [comment]
> This might actually be better solved in Rails. `build_explain_clause` should have been implemented on abstract_mysql_adapter, not mysql_adapter

I believe this PR does just that: https://github.com/rails/rails/pull/48112
