### ISSUE TITLE
Notice: This repository will be moving to the trilogy-libraries organisation

### ISSUE THREAD

**Issue by bensheldon** [trilogy-libraries/activerecord-trilogy-adapter#40]
# This repository is moving! 🚶🏻 

This repository is moving to a new github.com home: https://github.com/trilogy-libraries/activerecord-trilogy-adapter (there's nothing there right now)

## Why?

To improve security of GitHub's primary organization, https://github.com/github, GitHub is moving all repositories with outside collaborators to separate organizations. This repository is one of those.

## When?

We expect to perform this before June 1, 2023. 

## What will happen?

The repository in its entirety will be moved to the new organization at https://github.com/trilogy-libraries/activerecord-trilogy-adapter (there's nothing there right now).

All current external contributors will retain their access.

All PRs should automatically rebase to the new repository location so you shouldn't need to do anything. If they don't please comment here and we will fix it.

All issues and discussions will be moved across at the same time too.

**Comment by lorint** [comment]
Heya Ben!

Cool -- I'll check out the ActiveRecord 7.0 PR right away after the
transition.

Eager to get that one delivered, and start to look at support for Rails 6.1
:)

Thanks out to your team for all the feedback along the way.

-Lorin Thwaits

**Comment by bensheldon** [comment]
We have moved this repository 🚚 ✅ 

@lorint thank you! Your PR and a release is next on my list to work on :-)
